// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockVersionChecker is an autogenerated mock type for the VersionChecker type
type MockVersionChecker struct {
	mock.Mock
}

type MockVersionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionChecker) EXPECT() *MockVersionChecker_Expecter {
	return &MockVersionChecker_Expecter{mock: &_m.Mock}
}

// GetLatestVersion provides a mock function with given fields: ctx, modulePath
func (_m *MockVersionChecker) GetLatestVersion(ctx context.Context, modulePath string) (string, error) {
	ret := _m.Called(ctx, modulePath)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, modulePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, modulePath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, modulePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionChecker_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockVersionChecker_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - modulePath string
func (_e *MockVersionChecker_Expecter) GetLatestVersion(ctx interface{}, modulePath interface{}) *MockVersionChecker_GetLatestVersion_Call {
	return &MockVersionChecker_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion", ctx, modulePath)}
}

func (_c *MockVersionChecker_GetLatestVersion_Call) Run(run func(ctx context.Context, modulePath string)) *MockVersionChecker_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVersionChecker_GetLatestVersion_Call) Return(_a0 string, _a1 error) *MockVersionChecker_GetLatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionChecker_GetLatestVersion_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockVersionChecker_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVersionChecker creates a new instance of MockVersionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionChecker {
	mock := &MockVersionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
