// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/grigory/gomodinspect/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockInspector is an autogenerated mock type for the Inspector type
type MockInspector struct {
	mock.Mock
}

type MockInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInspector) EXPECT() *MockInspector_Expecter {
	return &MockInspector_Expecter{mock: &_m.Mock}
}

// Inspect provides a mock function with given fields: ctx, repoURL
func (_m *MockInspector) Inspect(ctx context.Context, repoURL string) (*domain.ModuleInfo, error) {
	ret := _m.Called(ctx, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 *domain.ModuleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ModuleInfo, error)); ok {
		return rf(ctx, repoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ModuleInfo); ok {
		r0 = rf(ctx, repoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ModuleInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInspector_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockInspector_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
func (_e *MockInspector_Expecter) Inspect(ctx interface{}, repoURL interface{}) *MockInspector_Inspect_Call {
	return &MockInspector_Inspect_Call{Call: _e.mock.On("Inspect", ctx, repoURL)}
}

func (_c *MockInspector_Inspect_Call) Run(run func(ctx context.Context, repoURL string)) *MockInspector_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInspector_Inspect_Call) Return(_a0 *domain.ModuleInfo, _a1 error) *MockInspector_Inspect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInspector_Inspect_Call) RunAndReturn(run func(context.Context, string) (*domain.ModuleInfo, error)) *MockInspector_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInspector creates a new instance of MockInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInspector {
	mock := &MockInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
