// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepoFetcher is an autogenerated mock type for the RepoFetcher type
type MockRepoFetcher struct {
	mock.Mock
}

type MockRepoFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoFetcher) EXPECT() *MockRepoFetcher_Expecter {
	return &MockRepoFetcher_Expecter{mock: &_m.Mock}
}

// FetchGoMod provides a mock function with given fields: ctx, repoURL
func (_m *MockRepoFetcher) FetchGoMod(ctx context.Context, repoURL string) ([]byte, error) {
	ret := _m.Called(ctx, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for FetchGoMod")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, repoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, repoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepoFetcher_FetchGoMod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchGoMod'
type MockRepoFetcher_FetchGoMod_Call struct {
	*mock.Call
}

// FetchGoMod is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
func (_e *MockRepoFetcher_Expecter) FetchGoMod(ctx interface{}, repoURL interface{}) *MockRepoFetcher_FetchGoMod_Call {
	return &MockRepoFetcher_FetchGoMod_Call{Call: _e.mock.On("FetchGoMod", ctx, repoURL)}
}

func (_c *MockRepoFetcher_FetchGoMod_Call) Run(run func(ctx context.Context, repoURL string)) *MockRepoFetcher_FetchGoMod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepoFetcher_FetchGoMod_Call) Return(_a0 []byte, _a1 error) *MockRepoFetcher_FetchGoMod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepoFetcher_FetchGoMod_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockRepoFetcher_FetchGoMod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoFetcher creates a new instance of MockRepoFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoFetcher {
	mock := &MockRepoFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
