// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/grigory/gomodinspect/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAnalysisCache is an autogenerated mock type for the AnalysisCache type
type MockAnalysisCache struct {
	mock.Mock
}

type MockAnalysisCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalysisCache) EXPECT() *MockAnalysisCache_Expecter {
	return &MockAnalysisCache_Expecter{mock: &_m.Mock}
}

// AllRepoURLs provides a mock function with given fields: ctx
func (_m *MockAnalysisCache) AllRepoURLs(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllRepoURLs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalysisCache_AllRepoURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllRepoURLs'
type MockAnalysisCache_AllRepoURLs_Call struct {
	*mock.Call
}

// AllRepoURLs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnalysisCache_Expecter) AllRepoURLs(ctx interface{}) *MockAnalysisCache_AllRepoURLs_Call {
	return &MockAnalysisCache_AllRepoURLs_Call{Call: _e.mock.On("AllRepoURLs", ctx)}
}

func (_c *MockAnalysisCache_AllRepoURLs_Call) Run(run func(ctx context.Context)) *MockAnalysisCache_AllRepoURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAnalysisCache_AllRepoURLs_Call) Return(_a0 []string, _a1 error) *MockAnalysisCache_AllRepoURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalysisCache_AllRepoURLs_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockAnalysisCache_AllRepoURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, repoURL
func (_m *MockAnalysisCache) Delete(ctx context.Context, repoURL string) error {
	ret := _m.Called(ctx, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, repoURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnalysisCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAnalysisCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
func (_e *MockAnalysisCache_Expecter) Delete(ctx interface{}, repoURL interface{}) *MockAnalysisCache_Delete_Call {
	return &MockAnalysisCache_Delete_Call{Call: _e.mock.On("Delete", ctx, repoURL)}
}

func (_c *MockAnalysisCache_Delete_Call) Run(run func(ctx context.Context, repoURL string)) *MockAnalysisCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAnalysisCache_Delete_Call) Return(_a0 error) *MockAnalysisCache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalysisCache_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAnalysisCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, repoURL
func (_m *MockAnalysisCache) Get(ctx context.Context, repoURL string) (*domain.AnalysisRecord, error) {
	ret := _m.Called(ctx, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.AnalysisRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AnalysisRecord, error)); ok {
		return rf(ctx, repoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AnalysisRecord); ok {
		r0 = rf(ctx, repoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AnalysisRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalysisCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAnalysisCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
func (_e *MockAnalysisCache_Expecter) Get(ctx interface{}, repoURL interface{}) *MockAnalysisCache_Get_Call {
	return &MockAnalysisCache_Get_Call{Call: _e.mock.On("Get", ctx, repoURL)}
}

func (_c *MockAnalysisCache_Get_Call) Run(run func(ctx context.Context, repoURL string)) *MockAnalysisCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAnalysisCache_Get_Call) Return(_a0 *domain.AnalysisRecord, _a1 error) *MockAnalysisCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalysisCache_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.AnalysisRecord, error)) *MockAnalysisCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, record
func (_m *MockAnalysisCache) Save(ctx context.Context, record *domain.AnalysisRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AnalysisRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnalysisCache_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAnalysisCache_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - record *domain.AnalysisRecord
func (_e *MockAnalysisCache_Expecter) Save(ctx interface{}, record interface{}) *MockAnalysisCache_Save_Call {
	return &MockAnalysisCache_Save_Call{Call: _e.mock.On("Save", ctx, record)}
}

func (_c *MockAnalysisCache_Save_Call) Run(run func(ctx context.Context, record *domain.AnalysisRecord)) *MockAnalysisCache_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AnalysisRecord))
	})
	return _c
}

func (_c *MockAnalysisCache_Save_Call) Return(_a0 error) *MockAnalysisCache_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalysisCache_Save_Call) RunAndReturn(run func(context.Context, *domain.AnalysisRecord) error) *MockAnalysisCache_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalysisCache creates a new instance of MockAnalysisCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalysisCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalysisCache {
	mock := &MockAnalysisCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
